# https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#docker

- name: Add nvidia-docker GPG key
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
  become: yes

- name: Add nvidia-docker stable apt repository
  shell: >
    curl -s -L 
    https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list 
    | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

- name: sudo apt update && sudo apt install nvidia-docker2
  apt:
    pkg: nvidia-container-toolkit
    state: present
    autoclean: yes
    update_cache: yes
  become: yes
  notify: restart docker daemon

- name: configure /etc/docker/daemon.json for nvidia-container-runtime
  shell: >
    nvidia-ctk runtime configure --runtime=docker
  become: yes
  notify: restart docker daemon
