- include_role:
    name: common

- name: Ensure {{ home_dir }}/.docker directory exists
  file:
    path: '{{ home_dir }}/.docker'
    state: directory

- name: Render config.json.j2 to {{ home_dir }}/.docker/config.json
  template:
    src: config.json.j2
    dest: '{{ home_dir }}/.docker/config.json'
