- name: "docker network create {{ opts }} {{ docker_network }}"
  shell: "docker network create {{ opts }} {{ docker_network }}"
  vars:
    opts: '{{ options.network_create }}'
  register: cmd
  failed_when: cmd.rc > 1

- name: "check idempotent case"
  fail: '{{ cmd }}'
  when: 'cmd.rc == 1 && "already exists" not in cmd.stderr.lower()'
