- name: "docker network create --driver=overlay --attachable {{ docker_network }}"
  shell: "docker network create --driver=overlay --attachable {{ docker_network }}"
  register: docker_net_init
  failed_when: docker_net_init.rc > 1
