- name: "docker service update {{ opts }} {{ docker_stack }}_{{ docker_service }}"
  shell: "docker service update {{ opts }} {{ docker_stack }}_{{ docker_service }}"
  vars:
    opts: '{{ options.service_update }}'
  register: docker_service_update
  failed_when: docker_service_update.rc > 1
