- include_role:
    name: application
    tasks_from: make_config_dir

- name: 'render {{ docker_compose_template }} to {{ config_dir }}/docker-compose.yaml'
  template:
    src: '{{ docker_compose_template }}'
    dest: '{{ config_dir }}/docker-compose.yaml'
    mode: '0740'

- name: 'docker stack deploy --prune -c docker-compose.yaml {{ docker_stack }}'
  shell: docker stack deploy --prune -c docker-compose.yaml {{ docker_stack }}
  args:
    chdir: '{{ config_dir }}'
