- name: "docker swarm init"
  shell: "docker swarm init {{ options }}"
  register: cmd
  vars:
    options: ''
  failed_when: '(cmd.rc > 1) or ("node is already part of a swarm" not in cmd.stderr.lower())'
