- name: "docker swarm init {{ options }}"
  shell: "docker swarm init {{ options }}"
  register: cmd
  vars:
    options: '{{ options.swarm_init }}'
  failed_when: '(cmd.rc > 1) or ("node is already part of a swarm" not in cmd.stderr.lower())'
