- name: docker system prune {{ opts }}
  shell: >
    docker system prune {{ opts }}
  vars:
    opts: '{{ options.system_prune }}'
  register: prune_output

- debug:
    msg: '{{ prune_output.stdout_lines }}'
