- name: docker system prune --force {{ options }}
  shell: >
    docker system prune --force {{ options }}
  vars:
    options: ''
  register: prune_output

- debug:
    msg: '{{ prune_output.stdout_lines }}'
